wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/southafrica2010/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/germany2006/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/koreajapan2002/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/france1998/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/usa1994/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/italy1990/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/mexico1986/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/spain1982/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/argentina1978/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/germany1974/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/mexico1970/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/england1966/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/chile1962/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/sweden1958/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/switzerland1954/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/brazil1950/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/france1938/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/italy1934/matches/index.html
wget -l1 -A 'index.html' -np -r http://es.fifa.com/tournaments/archive/worldcup/uruguay1930/matches/index.html
